### ISSUE TITLE
[Tiled] Layer type unsupported

### ISSUE THREAD

**Issue by weaversam8** [craftworkgames/MonoGame.Extended#222]
In attempting to render a Tiled map on the develop branch, I'm encountering this error:

```
System.NotSupportedException was unhandled
  HResult=-2146233067
  Message=Layer type  is not supported
  Source=MonoGame.Extended
  StackTrace:
       at MonoGame.Extended.Maps.Tiled.TiledMapReader.ReadLayerTypeProperties(ContentReader reader, TiledMap tiledMap, String layerName, String layerType)
       at MonoGame.Extended.Maps.Tiled.TiledMapReader.ReadLayer(ContentReader reader, TiledMap tiledMap)
       at MonoGame.Extended.Maps.Tiled.TiledMapReader.Read(ContentReader reader, TiledMap existingInstance)
       at Microsoft.Xna.Framework.Content.ContentTypeReader`1.Read(ContentReader input, Object existingInstance)
       at Microsoft.Xna.Framework.Content.ContentReader.InnerReadObject[T](T existingInstance)
       at Microsoft.Xna.Framework.Content.ContentReader.ReadObject[T]()
       at Microsoft.Xna.Framework.Content.ContentReader.ReadAsset[T]()
       at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject)
       at Microsoft.Xna.Framework.Content.ContentManager.Load[T](String assetName)
       at DungeonGame.Game.LoadContent() in C:\Users\Samuel\Documents\Xamarin\Projects\Dungeon\SharedProject1\Game.cs:line 65
       at Microsoft.Xna.Framework.Game.Initialize()
       at DungeonGame.Game.Initialize() in C:\Users\Samuel\Documents\Xamarin\Projects\Dungeon\SharedProject1\Game.cs:line 51
       at Microsoft.Xna.Framework.Game.DoInitialize()
       at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
       at Microsoft.Xna.Framework.Game.Run()
       at DungeonGame.Program.Main() in C:\Users\Samuel\Documents\Xamarin\Projects\Dungeon\DungeonWindows\Program.cs:line 18
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

This did not occur on the release branch, so there's clearly something different. With a look at where that error is generated, we see this code block:

https://github.com/craftworkgames/MonoGame.Extended/blob/e5e6659856c3ff6af90f65ff63df5dbe0742d46b/Source/MonoGame.Extended/Maps/Tiled/TiledMapReader.cs#L106

Which indicates that that function is not receiving the proper `layerType` parameter. Any ideas?

**Comment by LithiumToast** [comment]
https://github.com/craftworkgames/MonoGame.Extended/blob/e5e6659856c3ff6af90f65ff63df5dbe0742d46b/Source/MonoGame.Extended/Maps/Tiled/TiledMapReader.cs#L114

```
throw new NotSupportedException($"Layer type {layerType} is not supported");
```

Judging by the output you posted ("Layer type  is not supported") `layerType` is empty or possible null. You could put a breakpoint on the line where it throws and check what the value of `layerType` is. If t's invalid you can navigate the call stack backwards in VisualStudio to see where the value of `layerType` originates from.

**Comment by craftworkgames** [comment]
Could you post your TMX file here please. 

What version of Tiled did you use to create it?

**Comment by HyperionMT** [comment]
Can we also close this one?  There doesn't appear to be any problems with our existing TiledMaps demo maps (especially level01.tmx which has the image layer).

**Comment by craftworkgames** [comment]
Yep. Closed.
