### ISSUE TITLE
SharpDX FileNotFoundException when using nuget package with Windows 10 UWP project

### ISSUE THREAD

**Issue by Romans-I-XVI** [craftworkgames/MonoGame.Extended#409]
So if you create a brand new MonoGame Windows 10 Universal Project and then use Nuget to install MonoGame.Extended you get the error 

>  Could not load file or assembly 'SharpDX, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1' or one of its dependencies.
   at Microsoft.Xna.Framework.FrameworkDispatcher.Initialize()
   at Microsoft.Xna.Framework.FrameworkDispatcher.Update()
   at Microsoft.Xna.Framework.Game..ctor()
   at Game3.Game1..ctor()

I'm not sure what's happening when the nuget package is installed but it is confusing MonoGame somehow. When I don't install through nuget and reference the MonoGame.Extended dlls directly everything works fine.

![error](https://user-images.githubusercontent.com/3883656/27716206-57a9080e-5d02-11e7-9549-d6a3c52d6fd3.png)

**Comment by jonmseaman** [comment]
I was able to solve this by manually adding the SharpDX packages to the UWP project.
Not sure how to make a better fix currently.
