### ISSUE TITLE
Error while loading the assembly MonoGame.Extended.Content.Pipeline.dll in the MonoGame Pipeline tool

### ISSUE THREAD

**Issue by GiottoVerducci** [craftworkgames/MonoGame.Extended#666]
Following the instructions in the blog http://blog.dylanwilson.net/posts/2015/creating-custom-content-importers-for-the-monogame-pipeline/

I'm trying to add the reference to the pipeline in order to import the fnt files created by BMFont.

I have the following error in the tool

System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at MonoGame.Tools.Pipeline.PipelineTypes.ResolveAssemblies(IEnumerable`1 assemblyPaths)
   at MonoGame.Tools.Pipeline.PipelineTypes.Load(PipelineProject project)
   at MonoGame.Tools.Pipeline.PipelineController.ResolveTypes()
   at MonoGame.Tools.Pipeline.PipelineController.OnReferencesModified()
   at MonoGame.Tools.Pipeline.CellRefs.Edit(PixelLayout control)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at MonoGame.Tools.Pipeline.Program.Main(String[] args)

The assembly is MonoGame.Extended.Content.Pipeline.3.7.0\lib\netstandard2.0\MonoGame.Extended.Content.Pipeline.dll

MonoGame is version SDK 3.7.1.189

Visual Studio is 2019 but it shouldn't matter as the standalone tool crashes.

**Comment by VampireMonkey** [comment]
Getting the same error :
`/packages/MonoGame.Extended.Content.Pipeline.3.7.0/lib/netstandard2.0/MonoGame.Extended.Content.Pipeline.dll': Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.`

I just came back to a project that could compile before but now won't

**Comment by lithiumtoast** [comment]
The content pipeline also is known to be troublesome: https://github.com/craftworkgames/MonoGame.Extended/issues/495

Says there are loader exceptions? Can y'all `Retrieve the LoaderExceptions property for more information.`?

**Comment by craxal** [comment]
Forums posted that, if the assemblies are moved to the project root directory and referenced from there, the errors go away, which I can confirm. No idea why the location of the assemblies should matter.

https://community.monogame.net/t/solved-no-default-importer-tmx-files/12293

**Comment by VampireMonkey** [comment]
I fixed it by creating a new project and updating to monogame 3.8 and .net core 3.1

**Comment by lithiumtoast** [comment]
Closing as it should be resolved with 3.8. Let me know otherwise.
