### ISSUE TITLE
[Tiled] TiledMapRenderer Crash

### ISSUE THREAD

**Issue by AngelMunoz** [craftworkgames/MonoGame.Extended#689]
> I'm guessing this is related to #687 but I just want to be sure I'm not doing something crazy

I'm trying to render a file I have in tiled, but when I try to use the TiledMapRenderer it crashes with the following exception
```
System.Exception
  HResult=0x80131500
  Message=This MGFX effect is for an older release of MonoGame and needs to be rebuilt.
  Source=MonoGame.Framework
  StackTrace:
   at Microsoft.Xna.Framework.Graphics.Effect.ReadHeader(Byte[] effectCode, Int32 index)
   at Microsoft.Xna.Framework.Graphics.Effect..ctor(GraphicsDevice graphicsDevice, Byte[] effectCode, Int32 index, Int32 count)
   at MonoGame.Extended.Graphics.Effects.MatrixChainEffect..ctor(GraphicsDevice graphicsDevice, Byte[] byteCode)
   at MonoGame.Extended.Graphics.Effects.DefaultEffect..ctor(GraphicsDevice graphicsDevice)
   at MonoGame.Extended.Tiled.Renderers.TiledMapRenderer..ctor(GraphicsDevice graphicsDevice, TiledMap map)
   at FeX.Game.FeXGame.Draw(GameTime gameTime) in C:\Users\scyth\source\repos\FeX\FeX.Game\Game.fs:line 147
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at FeX.Game.Main.main(String[] argv) in C:\Users\scyth\source\repos\FeX\FeX.Game\Program.fs:line 12
```

These are the versions I'm using
```
nuget MonoGame.Extended 3.7.0
nuget MonoGame.Extended.Content.Pipeline 3.7.0
nuget MonoGame.Extended.Tiled 3.7.0
nuget MonoGame.Framework.DesktopGL 3.8.0.1641
nuget MonoGame.Content.Builder.Task 3.8.0.1641
nuget FSharp.Core 4.7.2
```
Let me know if this is related to different MonoGame versions or should this work and perhaps I'm doing something weird

Trying this on a C# project also causes the same issue
![image](https://user-images.githubusercontent.com/8684875/90451005-21895f80-e0a8-11ea-9e96-b04060169bae.png)

here's a repro repository if needed 
https://github.com/AngelMunoz/MonoGame.Extended.Tiled.Repro

**Comment by lithiumtoast** [comment]
@AngelMunoz 

https://github.com/craftworkgames/MonoGame.Extended/issues/686
https://github.com/craftworkgames/MonoGame.Extended/issues/687

**Comment by AngelMunoz** [comment]
@lithiumtoast Ah sorry for some reason didn't see #686 sorry about the dupe

got it thanks

**Comment by lithiumtoast** [comment]
No worries. I'll re-open the other ticket so this is less likely to happen to someone else.
