### ISSUE TITLE
`InvalidCastException` thrown when loading a `TiledMap`

### ISSUE THREAD

**Issue by craxal** [craftworkgames/MonoGame.Extended#728]
Using 3.8.0, I'm trying to leverage MonoGame.Extended for Tiled maps and tilesets. I've got the MGCB editor all set up and successfully building my Tiled map and tileset. However, when I launch my game:

```cs
Content.Load<TiledMap>("TestMap");
```

```
System.InvalidCastException: 'Unable to cast object of type 'System.String' to type 'MonoGame.Extended.Tiled.TiledMap'.'
   at Microsoft.Xna.Framework.Content.ContentReader.InnerReadObject[T](T existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.ReadObject[T]()
   at Microsoft.Xna.Framework.Content.ContentReader.ReadAsset[T]()
   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject)
   at Microsoft.Xna.Framework.Content.ContentManager.Load[T](String assetName)
   ...
```

Seems odd the object being returned by `TiledMapReader` would be a string and not a `TiledMap`. Am I doing something wrong, or is there a bug somewhere?

**Comment by AristurtleDev** [comment]
Closing this issue as part of the tilemap system replacement.

The legacy `TiledMap` implementation has been deprecated and is being fully replaced by the new format-agnostic tilemap architecture tracked in #1113.

No additional feature work or non-critical fixes are being made to the legacy system. The new `Tilemap` + parser + renderer architecture resolves this class of issues by design.

If you are still using `TiledMap`, please plan to migrate to the new tilemap API before the next major release, where the legacy system will be removed.

If after migrating to the new system you encounter equivalent behavior, please open a new issue referencing #1113 with a minimal repro.

Thank you.
