### ISSUE TITLE
Receiving "unable to read beyond the end of the stream" error when loading Tiled map with develop branch

### ISSUE THREAD

**Issue by tigurx** [craftworkgames/MonoGame.Extended#878]
I recently pulled the latest develop branch that included the switch to System.Text.Json. I am now getting the following error when loading a map at run-time:

`System.IO.EndOfStreamException: 'Unable to read beyond the end of the stream'.`

I think it may be having trouble reading the TiledMapObject properties, but have not had a chance to investigate further yet.

**Call Stack:**
```
System.IO.EndOfStreamException
  HResult=0x80070026
  Message=Unable to read beyond the end of the stream.
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowEndOfFileException() in /_/src/libraries/System.Private.CoreLib/src/System/ThrowHelper.cs:line 334
   at System.IO.BinaryReader.ReadString() in /_/src/libraries/System.Private.CoreLib/src/System/IO/BinaryReader.cs:line 285
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 13
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.ContentReaderExtensions.ReadTiledMapProperties(ContentReader reader, TiledMapProperties properties) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\ContentReaderExtensions.cs:line 15
   at MonoGame.Extended.Tiled.TiledMapTilesetReader.ReadTiledMapObject(ContentReader reader, TiledMapTileset tileset) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\TiledMapTilesetReader.cs:line 103
   at MonoGame.Extended.Tiled.TiledMapTilesetReader.ReadTile(ContentReader reader, TiledMapTileset tileset) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\TiledMapTilesetReader.cs:line 50
   at MonoGame.Extended.Tiled.TiledMapTilesetReader.ReadTileset(ContentReader reader) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\TiledMapTilesetReader.cs:line 33
   at Microsoft.Xna.Framework.Content.ContentTypeReader`1.Read(ContentReader input, Object existingInstance) in Microsoft.Xna.Framework.Content\ContentTypeReader.cs:line 35
   at Microsoft.Xna.Framework.Content.ContentReader.InnerReadObject[T](T existingInstance) in Microsoft.Xna.Framework.Content\ContentReader.cs:line 157
   at Microsoft.Xna.Framework.Content.ContentReader.ReadObject[T]() in Microsoft.Xna.Framework.Content\ContentReader.cs:line 131
   at Microsoft.Xna.Framework.Content.ContentReader.ReadAsset[T]() in Microsoft.Xna.Framework.Content\ContentReader.cs:line 46
   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject) in Microsoft.Xna.Framework.Content\ContentManager.cs:line 265
   at Microsoft.Xna.Framework.Content.ContentManager.Load[T](String assetName) in Microsoft.Xna.Framework.Content\ContentManager.cs:line 212
   at Microsoft.Xna.Framework.Content.ContentReader.ReadExternalReference[T]() in Microsoft.Xna.Framework.Content\ContentReader.cs:line 89
   at MonoGame.Extended.Tiled.TiledMapReader.ReadTilesets(ContentReader reader, TiledMap map) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\TiledMapReader.cs:line 47
   at MonoGame.Extended.Tiled.TiledMapReader.Read(ContentReader reader, TiledMap existingInstance) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended.Tiled\TiledMapReader.cs:line 20
   at Microsoft.Xna.Framework.Content.ContentTypeReader`1.Read(ContentReader input, Object existingInstance) in Microsoft.Xna.Framework.Content\ContentTypeReader.cs:line 35
   at Microsoft.Xna.Framework.Content.ContentReader.InnerReadObject[T](T existingInstance) in Microsoft.Xna.Framework.Content\ContentReader.cs:line 157
   at Microsoft.Xna.Framework.Content.ContentReader.ReadObject[T]() in Microsoft.Xna.Framework.Content\ContentReader.cs:line 131
   at Microsoft.Xna.Framework.Content.ContentReader.ReadAsset[T]() in Microsoft.Xna.Framework.Content\ContentReader.cs:line 46
   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject) in Microsoft.Xna.Framework.Content\ContentManager.cs:line 265
   at Microsoft.Xna.Framework.Content.ContentManager.Load[T](String assetName) in Microsoft.Xna.Framework.Content\ContentManager.cs:line 212
   at LunaShared.TiledEngine.LoadMap(Int32 mapNumber, ContentManager content) in C:\Users\tigur\source\repos\Luna\LunaShared\Engine\TiledEngine.cs:line 54
   at Luna.Classes.MainScreen.LoadContent() in C:\Users\tigur\source\repos\Luna\Luna\Classes\Screens\MainScreen.cs:line 67
   at MonoGame.Extended.Screens.ScreenManager.LoadScreen(Screen screen) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended\Screens\ScreenManager.cs:line 40
   at MonoGame.Extended.Screens.Transitions.Transition.Update(GameTime gameTime) in C:\Users\tigur\source\repos\MonoGame.Extended.Develop\src\cs\MonoGame.Extended\Screens\Transitions\Transition.cs:line 40
   at Microsoft.Xna.Framework.Game.SortingFilteringCollection`1.ForEachFilteredItem[TUserData](Action`2 action, TUserData userData)
   at Luna.Game1.Update(GameTime gameTime) in C:\Users\tigur\source\repos\Luna\Luna\Game1.cs:line 162
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in Microsoft.Xna.Framework\SdlGamePlatform.cs:line 73
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Program.<Main>$(String[] args) in C:\Users\tigur\source\repos\Luna\Luna\Program.cs:line 10

```
![error1](https://github.com/craftworkgames/MonoGame.Extended/assets/16768537/4a74e574-8b99-405e-900f-e9f06da851a0)
![error2](https://github.com/craftworkgames/MonoGame.Extended/assets/16768537/599a95ed-ca66-4a66-a56d-b661244e9647)
![error3](https://github.com/craftworkgames/MonoGame.Extended/assets/16768537/07641d58-ad9d-4cdb-9239-56e588308acc)

**Comment by kevld** [comment]
Hello, I have the same problem using the load method, any workaround ?
